apiVersion: apps/v1
kind: Deployment
metadata:
  name: edgartools-uat-deployment
spec:
  selector:
    matchLabels:
      app: edgartools-uat-pod
  template:
    metadata:
      labels:
        app: edgartools-uat-pod
    spec:
      containers:
      - name: edgartools-uat-container
        image: edgartools.azurecr.io/etback:uat1
        resources: 
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
